### ISSUE TITLE
💡[FEATURE] hover the navbar and footer social media icons

### ISSUE THREAD

**Issue by jayanththalla** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#151] opened 2024-06-01 16:42 UTC
### Description

hover the footer social media icons and the navbar about us and contact us

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/121346142/5ab04a82-1386-4dbf-a22c-590c0b7b041a)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Samik123Mit** [comment] 2024-06-05 00:17
pls, assign me the issue. I will make sure the task is done.

**Comment by dhananjay6561** [comment] 2024-07-27 04:10
@jayanththalla The issue is solved. You may close it.

**Closed** 2024-07-27 15:02 UTC
Labels: enhancement
